namespace Belediye_Otomasyonu.Views
{
    partial class PersonelYonetimForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TabControl tabAna;
        private System.Windows.Forms.TabPage tabListe;
        private System.Windows.Forms.DataGridView dgvPersonel;
        private System.Windows.Forms.FlowLayoutPanel flowListeButonlar;
        private System.Windows.Forms.Button btnListeYenile;
        private System.Windows.Forms.Button btnVatandasYetki;
        private System.Windows.Forms.Button btnDurumDegistir;
        private System.Windows.Forms.Button btnKapat;
        private System.Windows.Forms.TabPage tabYeni;
        private System.Windows.Forms.Label lblYeniKadi;
        private System.Windows.Forms.TextBox txtYeniKadi;
        private System.Windows.Forms.Label lblYeniSifre;
        private System.Windows.Forms.TextBox txtYeniSifre;
        private System.Windows.Forms.Label lblYeniAd;
        private System.Windows.Forms.TextBox txtYeniAd;
        private System.Windows.Forms.Label lblYeniSoyad;
        private System.Windows.Forms.TextBox txtYeniSoyad;
        private System.Windows.Forms.CheckBox chkYeniYonetici;
        private System.Windows.Forms.Button btnYeniKaydet;
        private System.Windows.Forms.Label lblDepLabel;
        private System.Windows.Forms.TextBox txtDepartman;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.tabAna = new System.Windows.Forms.TabControl();
            this.tabListe = new System.Windows.Forms.TabPage();
            this.flowListeButonlar = new System.Windows.Forms.FlowLayoutPanel();
            this.btnListeYenile = new System.Windows.Forms.Button();
            this.btnVatandasYetki = new System.Windows.Forms.Button();
            this.btnDurumDegistir = new System.Windows.Forms.Button();
            this.btnKapat = new System.Windows.Forms.Button();
            this.dgvPersonel = new System.Windows.Forms.DataGridView();
            this.tabYeni = new System.Windows.Forms.TabPage();
            this.btnYeniKaydet = new System.Windows.Forms.Button();
            this.chkYeniYonetici = new System.Windows.Forms.CheckBox();
            this.lblDepLabel = new System.Windows.Forms.Label();
            this.txtDepartman = new System.Windows.Forms.TextBox();
            this.txtYeniSoyad = new System.Windows.Forms.TextBox();
            this.lblYeniSoyad = new System.Windows.Forms.Label();
            this.txtYeniAd = new System.Windows.Forms.TextBox();
            this.lblYeniAd = new System.Windows.Forms.Label();
            this.txtYeniSifre = new System.Windows.Forms.TextBox();
            this.lblYeniSifre = new System.Windows.Forms.Label();
            this.txtYeniKadi = new System.Windows.Forms.TextBox();
            this.lblYeniKadi = new System.Windows.Forms.Label();
            this.tabAna.SuspendLayout();
            this.tabListe.SuspendLayout();
            this.flowListeButonlar.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPersonel)).BeginInit();
            this.tabYeni.SuspendLayout();
            this.SuspendLayout();
            this.tabAna.Controls.Add(this.tabListe);
            this.tabAna.Controls.Add(this.tabYeni);
            this.tabAna.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabAna.Location = new System.Drawing.Point(0, 0);
            this.tabAna.Name = "tabAna";
            this.tabAna.SelectedIndex = 0;
            this.tabAna.Size = new System.Drawing.Size(784, 461);
            this.tabAna.TabIndex = 0;
            this.tabListe.Controls.Add(this.dgvPersonel);
            this.tabListe.Controls.Add(this.flowListeButonlar);
            this.tabListe.Location = new System.Drawing.Point(4, 22);
            this.tabListe.Name = "tabListe";
            this.tabListe.Padding = new System.Windows.Forms.Padding(8);
            this.tabListe.Size = new System.Drawing.Size(776, 435);
            this.tabListe.TabIndex = 0;
            this.tabListe.Text = "Personel listesi";
            this.tabListe.UseVisualStyleBackColor = true;
            this.flowListeButonlar.Controls.Add(this.btnListeYenile);
            this.flowListeButonlar.Controls.Add(this.btnVatandasYetki);
            this.flowListeButonlar.Controls.Add(this.btnDurumDegistir);
            this.flowListeButonlar.Controls.Add(this.btnKapat);
            this.flowListeButonlar.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.flowListeButonlar.FlowDirection = System.Windows.Forms.FlowDirection.LeftToRight;
            this.flowListeButonlar.Location = new System.Drawing.Point(8, 387);
            this.flowListeButonlar.Name = "flowListeButonlar";
            this.flowListeButonlar.Padding = new System.Windows.Forms.Padding(0, 8, 0, 0);
            this.flowListeButonlar.Size = new System.Drawing.Size(760, 40);
            this.flowListeButonlar.TabIndex = 1;
            this.btnListeYenile.Location = new System.Drawing.Point(3, 11);
            this.btnListeYenile.Name = "btnListeYenile";
            this.btnListeYenile.Size = new System.Drawing.Size(100, 28);
            this.btnListeYenile.TabIndex = 0;
            this.btnListeYenile.Text = "Listeyi yenile";
            this.btnListeYenile.UseVisualStyleBackColor = false;
            this.btnListeYenile.Click += new System.EventHandler(this.btnListeYenile_Click);
            this.btnVatandasYetki.Location = new System.Drawing.Point(109, 11);
            this.btnVatandasYetki.Name = "btnVatandasYetki";
            this.btnVatandasYetki.Size = new System.Drawing.Size(200, 28);
            this.btnVatandasYetki.TabIndex = 1;
            this.btnVatandasYetki.Text = "Vatandaşa personel yetkisi ver";
            this.btnVatandasYetki.UseVisualStyleBackColor = false;
            this.btnVatandasYetki.Click += new System.EventHandler(this.btnVatandasYetki_Click);
            this.btnDurumDegistir.Location = new System.Drawing.Point(315, 11);
            this.btnDurumDegistir.Name = "btnDurumDegistir";
            this.btnDurumDegistir.Size = new System.Drawing.Size(160, 28);
            this.btnDurumDegistir.TabIndex = 2;
            this.btnDurumDegistir.Text = "Aktif / pasif değiştir";
            this.btnDurumDegistir.UseVisualStyleBackColor = false;
            this.btnDurumDegistir.Click += new System.EventHandler(this.btnDurumDegistir_Click);
            this.btnKapat.Location = new System.Drawing.Point(481, 11);
            this.btnKapat.Name = "btnKapat";
            this.btnKapat.Size = new System.Drawing.Size(100, 28);
            this.btnKapat.TabIndex = 3;
            this.btnKapat.Text = "Kapat";
            this.btnKapat.UseVisualStyleBackColor = false;
            this.btnKapat.Click += new System.EventHandler(this.btnKapat_Click);
            this.dgvPersonel.AllowUserToAddRows = false;
            this.dgvPersonel.AllowUserToDeleteRows = false;
            this.dgvPersonel.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvPersonel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvPersonel.Location = new System.Drawing.Point(8, 8);
            this.dgvPersonel.Name = "dgvPersonel";
            this.dgvPersonel.Size = new System.Drawing.Size(760, 379);
            this.dgvPersonel.TabIndex = 0;
            this.tabYeni.Controls.Add(this.btnYeniKaydet);
            this.tabYeni.Controls.Add(this.chkYeniYonetici);
            this.tabYeni.Controls.Add(this.txtYeniSoyad);
            this.tabYeni.Controls.Add(this.lblYeniSoyad);
            this.tabYeni.Controls.Add(this.txtYeniAd);
            this.tabYeni.Controls.Add(this.lblYeniAd);
            this.tabYeni.Controls.Add(this.txtYeniSifre);
            this.tabYeni.Controls.Add(this.lblYeniSifre);
            this.tabYeni.Controls.Add(this.txtYeniKadi);
            this.tabYeni.Controls.Add(this.lblYeniKadi);
            this.tabYeni.Location = new System.Drawing.Point(4, 22);
            this.tabYeni.Name = "tabYeni";
            this.tabYeni.Padding = new System.Windows.Forms.Padding(16);
            this.tabYeni.Size = new System.Drawing.Size(776, 435);
            this.tabYeni.TabIndex = 1;
            this.tabYeni.Text = "Yeni Personel Ekle";
            this.tabYeni.UseVisualStyleBackColor = true;
            this.lblYeniKadi.AutoSize = true;
            this.lblYeniKadi.Location = new System.Drawing.Point(19, 24);
            this.lblYeniKadi.Name = "lblYeniKadi";
            this.lblYeniKadi.Size = new System.Drawing.Size(64, 13);
            this.lblYeniKadi.Text = "Kullanıcı adı";
            this.txtYeniKadi.Location = new System.Drawing.Point(140, 21);
            this.txtYeniKadi.Name = "txtYeniKadi";
            this.txtYeniKadi.Size = new System.Drawing.Size(260, 20);
            this.txtYeniKadi.TabIndex = 0;
            this.lblYeniSifre.AutoSize = true;
            this.lblYeniSifre.Location = new System.Drawing.Point(19, 56);
            this.lblYeniSifre.Name = "lblYeniSifre";
            this.lblYeniSifre.Size = new System.Drawing.Size(28, 13);
            this.lblYeniSifre.Text = "Şifre";
            this.txtYeniSifre.Location = new System.Drawing.Point(140, 53);
            this.txtYeniSifre.Name = "txtYeniSifre";
            this.txtYeniSifre.PasswordChar = '●';
            this.txtYeniSifre.Size = new System.Drawing.Size(260, 20);
            this.txtYeniSifre.TabIndex = 1;
            this.lblYeniAd.AutoSize = true;
            this.lblYeniAd.Location = new System.Drawing.Point(19, 88);
            this.lblYeniAd.Name = "lblYeniAd";
            this.lblYeniAd.Size = new System.Drawing.Size(20, 13);
            this.lblYeniAd.Text = "Ad";
            this.txtYeniAd.Location = new System.Drawing.Point(140, 85);
            this.txtYeniAd.Name = "txtYeniAd";
            this.txtYeniAd.Size = new System.Drawing.Size(260, 20);
            this.txtYeniAd.TabIndex = 2;
            this.lblYeniSoyad.AutoSize = true;
            this.lblYeniSoyad.Location = new System.Drawing.Point(19, 120);
            this.lblYeniSoyad.Name = "lblYeniSoyad";
            this.lblYeniSoyad.Size = new System.Drawing.Size(37, 13);
            this.lblYeniSoyad.Text = "Soyad";
            this.txtYeniSoyad.Location = new System.Drawing.Point(140, 117);
            this.txtYeniSoyad.Name = "txtYeniSoyad";
            this.txtYeniSoyad.Size = new System.Drawing.Size(260, 20);
            this.txtYeniSoyad.TabIndex = 3;
            this.chkYeniYonetici.AutoSize = true;
            this.chkYeniYonetici.Location = new System.Drawing.Point(140, 152);
            this.chkYeniYonetici.Name = "chkYeniYonetici";
            this.chkYeniYonetici.Size = new System.Drawing.Size(220, 17);
            this.chkYeniYonetici.TabIndex = 4;
            this.chkYeniYonetici.Text = "Yönetici (kaldırıldı — ayrı tablo)";
            this.chkYeniYonetici.Visible = false;
            this.chkYeniYonetici.UseVisualStyleBackColor = true;
            this.lblDepLabel.AutoSize = true;
            this.lblDepLabel.Location = new System.Drawing.Point(19, 152);
            this.lblDepLabel.Name = "lblDepLabel";
            this.lblDepLabel.Size = new System.Drawing.Size(60, 13);
            this.lblDepLabel.Text = "Departman";
            this.txtDepartman.Location = new System.Drawing.Point(140, 149);
            this.txtDepartman.Name = "txtDepartman";
            this.txtDepartman.Size = new System.Drawing.Size(260, 20);
            this.txtDepartman.TabIndex = 4;
            this.btnYeniKaydet.Location = new System.Drawing.Point(140, 192);
            this.btnYeniKaydet.Name = "btnYeniKaydet";
            this.btnYeniKaydet.Size = new System.Drawing.Size(180, 36);
            this.btnYeniKaydet.TabIndex = 5;
            this.btnYeniKaydet.Text = "Personeli Kaydet";
            this.btnYeniKaydet.UseVisualStyleBackColor = false;
            this.btnYeniKaydet.Click += new System.EventHandler(this.btnYeniKaydet_Click);
            this.tabYeni.Controls.Add(this.lblDepLabel);
            this.tabYeni.Controls.Add(this.txtDepartman);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.ClientSize = new System.Drawing.Size(784, 461);
            this.Controls.Add(this.tabAna);
            this.MinimumSize = new System.Drawing.Size(640, 400);
            this.Name = "PersonelYonetimForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Personel kullanıcı yönetimi";
            this.Load += new System.EventHandler(this.PersonelYonetimForm_Load);
            this.tabAna.ResumeLayout(false);
            this.tabListe.ResumeLayout(false);
            this.flowListeButonlar.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvPersonel)).EndInit();
            this.tabYeni.ResumeLayout(false);
            this.tabYeni.PerformLayout();
            this.ResumeLayout(false);
        }
    }
}
